name: Linux

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: linux
          target: desktop
          arch: gcc_64

      - name: Configure CMake
        run: cmake --preset linux

      - name: Build the library.
        run: cmake --build --preset linux

      - name: Build the Sandbox app.
        run: cmake --build --preset linux-sandbox
