name: Linux

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  # CMake build type (Release, Debug, RelWithDebInfo, etc.).
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        # Checks out the repository.
        uses: actions/checkout@v4

      - name: Install Qt
        # Installs the Qt SDK.
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'

      - name: Configure CMake
        # Configures CMake in a 'build' subdirectory.
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Builds the library.
        # Builds with the given configuration.
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Builds the Sandbox app.
        # Builds the sandbox app with the given configuration.
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target sandbox
