name: Windows

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  # CMake build type (Release, Debug, RelWithDebInfo, etc.).
  BUILD_TYPE: Release
  GENERATOR: Visual Studio 17 2022
  QT_VERSION: '5.15.2'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check Out
        # Checks out the repository.
        uses: actions/checkout@v4

      - name: Install Qt
        # Installs the Qt SDK.
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{env.QT_VERSION}}
          host: windows
          target: desktop

      - name: Configure CMake
        # Configures CMake in a 'build' subdirectory.
        run: cmake -B ${{github.workspace}}/build -G "${{env.GENERATOR}}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Builds the library.
        # Builds with the given configuration.
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Builds the Sandbox app.
        # Builds the sandbox app with the given configuration.
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target sandbox
