name: Windows

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Configure CMake
        run: cmake --preset windows

      - name: Build the library.
        run: cmake --build --preset windows

      - name: Build the Sandbox app.
        run: cmake --build --preset windows-sandbox
